### ISSUE TITLE
fixef

### ISSUE THREAD

**Issue by arives** [daijiang/phyr#29]
Daijiang,

Could you please change the function fixef so that it doesn't conflict with fixef in lme4? Is there an easy way to do this, allowing fixef to identify the class of object?

Thanks, Tony

**Comment by daijiang** [comment]
Changed it to `fixed_effects()`.

**Comment by arives** [comment]
Daijiang,

Couldn't you do this like "fixef.communityPGLMM" so that it wouldn't interfere with fixef in lme4?

Tony

______________
Anthony R. Ives
UW-Madison
459 Birge Hall
608-262-1519

**Comment by daijiang** [comment]
Tony,
I tried to, but importing `fixef` from nlme package failed. There are some annoying issues such as some functions are not exported from nlme namespace. I did not know how to deal with it yet (the issue maintained even I imported the whole nlme package). So instead, I just changed the function name to `fixed_effects` (`fixed.effects` is an alias in nlme (and thus lme4)). Is this okay?
Daijiang

**Comment by arives** [comment]
Great. So you managed to fix fixef in nlme?

**Comment by daijiang** [comment]
Sort of. I ended with still import fixef from lme4, which was in turn imported from nlme. But I think it works now. ba59852457570e3ab124eba9351ec7a7ac1df458

**Comment by arives** [comment]
Ugh. Complicated.
