### ISSUE TITLE
communityPGLMM does not accept a covariance matrix 

### ISSUE THREAD

**Issue by rdinnager** [daijiang/phyr#5]
`tree` parameter currently only accepts a `phylo` object. For flexibility, it would be good if the user can specify their own covariance matrix here as an alternative.

**Comment by daijiang** [comment]
I can relax this later. At this moment, users can specify their own `random.terms` if they want, but not the `tree` argument. I will deal with this later.

**Comment by rdinnager** [comment]
Oh right. Yes, a workaround would be to use a custom `random.effects' object, I should have realized. Okay, I'll use that in the mean-time.
