### ISSUE TITLE
Critical bug in pglmm_compare

### ISSUE THREAD

**Issue by j-iranzo** [daijiang/phyr#88]
The code of pglmm_compare has a critical bug in line 289. As a consequence, pglmm_compare produces wrong results if the rows of the original data table were not already sorted as the tips of the tree. An easy way to check that something is wrong is by randomly shuffling the rows of the input data table and running pglmm_compare: different results are obtained each time.

To fix the bug, the inputs of the 'match' function in line 289 should be reversed:
data <- data[match(phy$tip.label, sp),]

It is straightforward to check that the original line of code does not sort the rows of data as the tips of the phylogenetic tree, while the corrected line does,

**Comment by daijiang** [comment]
Thanks!! Fixed it.

**Comment by arives** [comment]
This was probably my fault in the first place. Thanks for finding it, and sorry for the hassle!

From: Daijiang Li ***@***.***>
Date: Friday, July 7, 2023 at 11:12 AM
To: daijiang/phyr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [daijiang/phyr] Critical bug in pglmm_compare (Issue #88)

Thanks!! Fixed it.

**Comment by rdinnager** [comment]
Maybe we should add a test to make sure this bug doesn't crop up again anywhere? Maybe just a test that randomizes the order of the data and then makes sure that all of the main functions return the same answer?
